#ifndef KISS_CPU_KERNEL_DISPATCH_CONNECTION_HANDLER_H
#define KISS_CPU_KERNEL_DISPATCH_CONNECTION_HANDLER_H

void initialize_cpu_dispatch_threads();
void free_dispatch_thread();

#endif //KISS_CPU_KERNEL_DISPATCH_CONNECTION_HANDLER_H
